import type { Metadata } from "next";
import "./globals.css";
import {Assistant} from 'next/font/google'


const assistantFont = Assistant({
  subsets: ['latin'],
  weight: ['200','300','400','500','600','700','800'],
  display: 'swap'
  
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${assistantFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
